// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBECb5CWLO6PyRu9AhjGqoJL713BImokdg',
    appId: '1:639454168205:web:4e34dbf6b3536373de8ec4',
    messagingSenderId: '639454168205',
    projectId: 'notely-15c49',
    authDomain: 'notely-15c49.firebaseapp.com',
    storageBucket: 'notely-15c49.appspot.com',
    measurementId: 'G-M1SFDT1T61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByRedDznzdvUkde8cGjW-TaHY8EBBoI64',
    appId: '1:639454168205:android:ce38ddcbb302349ede8ec4',
    messagingSenderId: '639454168205',
    projectId: 'notely-15c49',
    storageBucket: 'notely-15c49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxebnCoQGFb7I_FJzZj35tds3dYJZ_ypc',
    appId: '1:639454168205:ios:fc50150e32fb3f6fde8ec4',
    messagingSenderId: '639454168205',
    projectId: 'notely-15c49',
    storageBucket: 'notely-15c49.appspot.com',
    iosClientId: '639454168205-dqjud2d4uv83hp7megctilmnjapnu8sd.apps.googleusercontent.com',
    iosBundleId: 'ch.aelgict.notely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxebnCoQGFb7I_FJzZj35tds3dYJZ_ypc',
    appId: '1:639454168205:ios:fc50150e32fb3f6fde8ec4',
    messagingSenderId: '639454168205',
    projectId: 'notely-15c49',
    storageBucket: 'notely-15c49.appspot.com',
    iosClientId: '639454168205-dqjud2d4uv83hp7megctilmnjapnu8sd.apps.googleusercontent.com',
    iosBundleId: 'ch.aelgict.notely',
  );
}
